title: MrQR Docs
description: Quickstart & User Guides for MrQR
theme: just-the-docs

url: https://mrqr.me

aux_links: # remove if you don't want this link to appear on your pages
  Visis MrQR: https://mrqr.me
