title: MrQR Docs
description: Quickstart & User Guides for MrQR
remote_theme: just-the-docs

url: https://mrqr.me

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/mrqr-me/docs
